version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: dev_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: spring_api
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata: